r"""
EXIF data

generated by json2python-models v0.2.1 at Wed Sep 29 15:30:53 2021
command: /Users/tom/.local/share/virtualenvs/PhotoOps-5MqeThcN/bin/json2models -s nested --datetime --max-strings-literals 0 -f dataclasses -m ExifData data/events/GetExifData-output.json
"""
from dataclasses import dataclass, field
from json_to_models.dynamic_typing import IntString, IsoTimeString
from typing import Any, List, Optional, Union


@dataclass
class IfdBase:
    '''IFD base class'''


@dataclass
class Ifd(IfdBase):
    @dataclass
    class Exif(IfdBase):
        exposure_time: float
        f_number: float
        exposure_program: str
        photographic_sensitivity: List[int]
        sensitivity_type: str
        recommended_exposure_index: int
        date_time_original: IsoTimeString
        date_time_digitized: IsoTimeString
        offset_time: IsoTimeString
        offset_time_original: IsoTimeString
        offset_time_digitized: IsoTimeString
        exposure_bias_value: float
        max_aperture_value: float
        metering_mode: str
        light_source: str
        flash: str
        focal_length: float
        user_comment: str
        sub_sec_time: IntString
        sub_sec_time_original: IntString
        sub_sec_time_digitized: IntString
        sensing_method: str
        file_source: str
        scene_type: str
        cva_pattern: List[int]
        custom_rendered: str
        exposure_mode: str
        white_balance: str
        focal_length_in35mm_film: int
        scene_capture_type: str
        gain_control: str
        contrast: str
        saturation: str
        sharpness: str
        subject_distance_range: str

    @dataclass
    class Gps(IfdBase):
        gps_version_id: List[int]
        gps_latitude_ref: str
        gps_latitude: List[float]
        gps_longitude_ref: str
        gps_longitude: List[float]
        gps_altitude_ref: int
        gps_altitude: float
        gps_time_stamp: List[float]
        gps_satellites: IntString
        gps_map_datum: str
        gps_date: str

    @dataclass
    class MakerNote(IfdBase):
        makernote_version: IntString
        quality: str
        whitebalance: str
        focus_mode: str
        flash_setting: str
        auto_flash_mode: str
        white_balance_bias: List[int]
        white_balance_rb_coeff: List[float]
        program_shift: str
        exposure_difference: str
        nikon_preview: int
        flash_compensation: str
        external_flash_exposure_comp: str
        flash_bracket_compensation_applied: str
        ae_bracket_compensation_applied: float
        crop_hi_speed: List[Union[int, str]]
        exposure_tuning: List[int]
        serial_number: IntString
        color_space: str
        vr_info: List[int]
        active_d_lighting: str
        picture_control: List[int]
        world_time: List[int]
        iso_info: List[int]
        vignette_control: str
        distort_info: List[int]
        unknown_info: List[int]
        multi_exposure_white_balance: List[float]
        tag0x003_c: List[int]
        black_level: List[int]
        image_size_raw: str
        tag0x003_f: List[float]
        tag0x0040: List[int]
        tag0x0041: List[int]
        tag0x0042: List[int]
        tag0x0043: List[int]
        tag0x0044: List[int]
        crop_area: List[int]
        tag0x0046: List[int]
        tag0x0047: List[int]
        tag0x0049: List[int]
        tag0x004_c: List[int]
        tag0x004_d: List[int]
        nikon_settings: List[Any]
        lens_type: str
        lens_min_max_focal_max_aperture: List[float]
        flash_mode: str
        shooting_mode: int
        auto_bracket_release: int
        lens_f_stops: List[int]
        nef_curve1: List[int]
        shot_info: List[Any]
        compression: str
        noise_reduction: str
        nef_curve2: List[int]
        color_balance: List[Any]
        lens_data: List[int]
        raw_image_center: List[int]
        retouch_history: List[int]
        tag0x00_a3: List[int]
        tag0x00_a4: List[int]
        total_shutter_releases: int
        flash_info: List[int]
        digital_vari_program: str
        multi_exposure: List[int]
        high_iso_noise_reduction: str
        power_up_time: List[int]
        af_info2: List[int]
        file_info: List[int]
        af_tune: List[int]
        retouch_info: List[int]
        tag0x00_bc: List[Any]
        tag0x00_bf: List[int]
        tag0x00_c0: List[int]

    @dataclass
    class SubIfd0_SubIfd2:
        subfile_type: str
        compression: str
        x_resolution: float
        y_resolution: float
        resolution_unit: str
        thumbnail_offset: int
        thumbnail_length: int
        y_cb_cr_positioning: str

    subfile_type: str
    image_width: int
    image_length: int
    bits_per_sample: List[int]
    compression: str
    photometric_interpretation: str
    strip_offsets: List[int]
    samples_per_pixel: int
    rows_per_strip: int
    strip_byte_counts: List[int]
    x_resolution: float
    y_resolution: float
    planar_configuration: str
    resolution_unit: str
    make: Optional[str] = None
    model: Optional[str] = None
    orientation: Optional[str] = None
    software: Optional[str] = None
    date_time: Optional[IsoTimeString] = None
    artist: Optional[str] = None
    sub_if_ds: Optional[List[int]] = field(default_factory=list)
    reference_black_white: Optional[List[float]] = field(default_factory=list)
    application_notes: Optional[List[Any]] = field(default_factory=list)
    copyright: Optional[str] = None
    exif_offset: Optional[int] = None
    gps_info: Optional[int] = None
    date_time_original: Optional[IsoTimeString] = None
    tiffep_standard_id: Optional[List[int]] = field(default_factory=list)
    exif: Optional['Exif_1H'] = None
    gps: Optional['Gps'] = None
    maker_note: Optional['MakerNote'] = None
    cfa_repeat_pattern_dim: Optional[List[int]] = field(default_factory=list)
    cfa_pattern2: Optional[List[int]] = field(default_factory=list)
    sensing_method: Optional[str] = None

    sub_ifd0: Optional['SubIfd0_SubIfd2'] = None
    sub_ifd1: Optional['ExifData.Ifd0_SubIfd1'] = None
    sub_ifd2: Optional['SubIfd0_SubIfd2'] = None

@dataclass
class Exif:
    '''EXIF data'''
    ifd0: Ifd


@dataclass
class Item:
    '''EFIX data item'''
    pk: str
    sk: str
    exif: Exif



