r"""
Image data

generated by json2python-models v0.2.1 at Wed Sep 29 13:26:30 2021
command: /Users/tom/.local/share/virtualenvs/PhotoOps-5MqeThcN/bin/json2models -s nested --datetime --max-strings-literals 0 -f dataclasses -m ImageExifData data/events/GetExifImageData-output.json
"""
from dataclasses import dataclass
from json_to_models.dynamic_typing import IsoTimeString
from typing import List, Optional

from .put_ddb_item import PutDdbItemAction


@dataclass
class ImageExifData:
    '''Image EXIF data'''
    compression: Optional[str]
    length: Optional[int]
    width: Optional[int]
    orientation: Optional[str]
    date_time: Optional[IsoTimeString]
    date_time_offset: Optional[IsoTimeString]
    auto_focus: Optional[bool]
    exposure_mode: Optional[str]
    exposure_program: Optional[str]
    exposure_time: Optional[float]
    flash: Optional[str]
    fnumber: Optional[float]
    focal_length: Optional[float]
    focal_length_in_35mm_film: Optional[int]
    photographic_sensitivity: List[int]
    light_source: Optional[str]
    metering_mode: Optional[str]
    sensing_method: Optional[str]
    sensitivity_type: Optional[str]
    contrast: Optional[str]
    gain_control: Optional[str]
    saturation: Optional[str]
    sharpness: Optional[str]
    subject_distance_range: Optional[str]
    white_balance: Optional[str]


@dataclass
class ImageExifDataItem(ImageExifData):
    '''Image EXIF data DDB item'''
    pk: Optional[str] = ''
    sk: Optional[str] = ''