r"""
Lens data

generated by json2python-models v0.2.1 at Wed Sep 29 13:25:39 2021
command: /Users/tom/.local/share/virtualenvs/PhotoOps-5MqeThcN/bin/json2models -s nested --datetime --max-strings-literals 0 -f dataclasses -m LensExifData data/events/GetExifLensData-output.json
"""
from dataclasses import dataclass, field
from typing import List
from typing import List, Optional, Union

from .put_ddb_item import PutDdbItemAction


@dataclass
class LensExifData:
    '''Lens EXIF data'''
    make: Optional[str]
    model: Optional[str]
    serial_number: Optional[str]
    min_focal: Optional[int]
    max_focal: Optional[int]
    min_aperture: Optional[float]
    max_aperture_high: Optional[float]
    max_aperture_low: Optional[float]
    auto_focus: Optional[bool]
    vibration_reduction: Optional[bool]
    lens_maker_type: List[str]
    camera_maker_type: List[str]
    macro: Optional[bool]
    zoom: Optional[bool]


@dataclass
class LensExifDataItem(LensExifData):
    '''Camera EXIF data DDB item'''
    pk: str = ''
    sk: str = ''